// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// i2s_sck //
// ------- //

#define i2s_sck_wrap_target 0
#define i2s_sck_wrap 1

static const uint16_t i2s_sck_program_instructions[] = {
            //     .wrap_target
    0xe001, //  0: set    pins, 1                    
    0xe000, //  1: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_sck_program = {
    .instructions = i2s_sck_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config i2s_sck_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_sck_wrap_target, offset + i2s_sck_wrap);
    return c;
}
#endif
